### ISSUE TITLE
Why Downsample?

### ISSUE THREAD

**Issue by amirshams84** [crazyhottommy/pyflow-ChIPseq#1]
Hi Ming
It would be great if you let me know why downsample

**Comment by crazyhottommy** [comment]
Hi, 
When you sequence a lot of samples and they do not have the same sequencing depth, you want to downsample them to the same read depth. see method in this paper https://www.nature.com/articles/nature14248 if you do not want to downsample, just set https://github.com/crazyhottommy/pyflow-ChIPseq/blob/master/config.yaml#L15 to a big number.

**Comment by amirshams84** [comment]
don't you think it will decrease the diversity and richness of the samples aka sensitivity

**Comment by crazyhottommy** [comment]
it will decrease the richness of course. but when you do downstream analysis say chromHMM which needs data from all different histone modifications, you want samples to have similar read depth. It depends on what you want to do.

**Comment by amirshams84** [comment]
Got It thanks

**Comment by crazyhottommy** [comment]
close now and you can open when you have other questions.
