### ISSUE TITLE
Using pipeline on SLURM?

### ISSUE THREAD

**Issue by sdjebali** [crazyhottommy/pyflow-ChIPseq#3]
Dear all,
thanks for this nice pipeline, it will be very useful to the community.
I was just wondering if this pipeline could be used on a SLURM job scheduling system?
Best,
Sarah

**Comment by crazyhottommy** [comment]
Hi Sarah, 
I totally missed this. Yes, it was designed to run on SLURM. You want to use a different branch https://github.com/crazyhottommy/pyflow-ChIPseq/tree/pairend
edit https://github.com/crazyhottommy/pyflow-ChIPseq/blob/pairend/cluster.json

and do 

```bash
snakemake -np

# if dry run works
./pyflow-ChIPseq.sh
```

https://github.com/crazyhottommy/pyflow-ChIPseq/blob/pairend/pyflow-ChIPseq.sh

If you have problems, please let me know.
